import type { InferGetStaticPropsType, NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import { getAllTags } from '../../lib/api'

type Props = InferGetStaticPropsType<typeof getStaticProps>

export const getStaticProps = async () => {
  return {
    props: {
      allTags: getAllTags()
    },
  }
}

const TagsIndex: NextPage<Props> = ({ allTags }) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          tags
        </h1>

        <ul>
          {allTags.map((tag) => (
            <li key={tag}>
              <Link href={`/tags/${tag}`}>
                <a>{tag}</a>
              </Link>
            </li>
          ))}
        </ul>
      </main>
    </div>
  )
}

export default TagsIndex
